- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - build-essential
  - python-setuptools
  - mysql-client
  - php7.0-mbstring
  - php-mysql
  - php-cli
  - php-mcrypt
  - php-json
  - php-curl
  - python3-pip
  - php-fpm
  - libmysqlclient-dev
  register: phpInstalled

- name: enable php mycrypt
  raw: phpenmod mcrypt
  when: phpInstalled | success

- name: copy php.ini to /etc/php/7.0/fpm/
  template:
    src: php.ini.j2
    dest: /etc/php/7.0/fpm/
    mode: 0755
    backup: yes
  when: phpInstalled | success

- name: restart php-fpm
  service:
    name: php7.0-fpm
    state: restarted
  when: phpInstalled | success
