---
- name: Install git,
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
  - git
  - unzip
  - composer
  - libapache2-mod-php7.0
  - ruby
  - python-pip
  - python-dev

- pip: name={{ item }}
  with_items:
    - virtualenv
