- name: Install Apache2
  apt:
    name: apache2
    state: latest
  register: apache2Installed

- name: remove default conf from apache sites-enabled
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  when: apache2Installed | success


- name: enabled mod_rewrite
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
  - rewrite
  - proxy
  - proxy_http

- name: copy apache sites-available default conf
  template:
    src: skosmos.conf.j2
    dest: /etc/apache2/sites-available/skosmos.conf
    backup: yes
  when: apache2Installed | success

- name: copy apache sites-available default conf
  file:
    src: /etc/apache2/sites-available/skosmos.conf
    dest: /etc/apache2/sites-enabled/skosmos.conf
    state: link
  when: apache2Installed | success

- name: remove default conf from apache sites-available
  file:
    path: /etc/apache2/sites-available/000-default.conf
    state: absent
  when: apache2Installed | success

- name: copy info.php to webroot
  template:
    src: info.php.j2
    dest: /var/www/skosmos/info.php
    mode: 0755

- name: restart apache2
  service:
    name: apache2
    state: restarted
