- name: Install Apache2
  apt:
    name: apache2
    state: latest
  register: apache2Installed

- name: enabled mod_rewrite
  apache2_module:
    name: rewrite
    state: present

- name: copy apache sites-available default conf
  template:
    src: skosmos.conf.j2
    dest: /etc/apache2/sites-available/skosmos.conf
    backup: yes
  when: apache2Installed | success

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: copy info.php to webroot
  template:
    src: info.php.j2
    dest: /var/www/html/info.php
    mode: 0755
  notify: restart apache2
