---
- file: path=/home/skosmos/srv/checkout mode=0755 state=directory

- name: send key to remote deploy user
  copy: src=keys/skosmos dest=/home/skosmos/.ssh/priv_key mode=0600

- name: checkout from bitbucket
  git: repo=git@github.com:devinit/skosmos.git dest=/var/www/skosmos key_file=/home/skosmos/.ssh/priv_key accept_hostkey=true force=yes

- name : updating dependencies with composer
  composer:
    command: update
    working_dir: /var/www/skosmos
    no_dev: True

- name : install dependencies with composer
  composer:
    command: install
    working_dir: /var/www/skosmos
    no_dev: True
